export enum CategoriesEnum {
  CARPINTERO = 'carpintero',
  ELECTRICISTA = 'electricista',
  LAVADERO = 'lavadero',
  MECANICO = 'mecanico',
  REPARACIONES = 'reparaciones',
  PLOMERIA = 'plomeria',
  PELUQUERIA = 'peluqueria',
  PERSONAL_TRAINER = 'personal trainer',
  JARDINERO = 'jardinero',
  GASISTA = 'gasista',
  DJ = 'DJ',
  PROGRAMADOR = 'programador',
  SALUD = 'salud',
  CHOFER = 'chofer',
  PASEADOR_MASCOTAS = 'paseador mascotas',
  PROFESOR_PARTICULAR = 'profesor particular',
  LIMPIEZA = 'limpieza',
  OTROS = 'otros',
}
